# tanh
https://vimsky.com/examples/usage/numpy-tanh-python.html

In [34]:
  
import numpy as np 
import math 
  
in_array = [0, math.pi / 2, np.pi / 3, np.pi] 
print ("Input array : \n", in_array) 
  
tanh_Values = np.tanh(in_array) 
print ("\nTangent Hyperbolic values : \n", tanh_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Tangent Hyperbolic values : 
 [0.         0.91715234 0.78071444 0.99627208]


In [40]:
# 反双曲正切（反函数）
print(np.arctanh(0.99)-np.arctanh(0.98))
print(np.arctanh(0.98))
print(np.arctanh(0.99))


0.34909248729495124
2.2975599250672945
2.6466524123622457


In [44]:
print(np.arctanh(0.98)) # 2.2975599250672945
for x in np.arange(np.arctanh(0.98), np.arctanh(0.99), 0.000001)[::-1]:
    if(np.tanh(x)-0.98 <1e-3):
        print(x, np.tanh(x))
        print("diff:", x -np.arctanh(0.98))
        break

2.2975599250672945
2.3234589250709146 0.9809999959088231
diff: 0.02589900000362011


In [33]:
print(np.arange(np.arctanh(0.98), np.arctanh(0.99), 0.000001))

print(np.arange(np.arctanh(0.98), np.arctanh(0.99), 0.000001)[::-1])

[2.29755993 2.29756093 2.29756193 ... 2.64664993 2.64665093 2.64665193]
[2.64665193 2.64665093 2.64664993 ... 2.29756193 2.29756093 2.29755993]
