## npy和npz的写入
https://www.yuque.com/huangzhongqing/hre6tf/vfm9f8


In [15]:
import numpy as np

a = np.arange(12).reshape(3,4)
b = np.arange(2)
c = np.arange(5)

np.save('test.npy',a)
# npz文件——压缩文件
# 使用np.savez()函数可以将多个数组保存到同一个文件中。
np.savez('testz.npz', a, b, c)
# 如若想给保存的数组命名，而不是默认的“arr_0”、“arr_1”、“arr_2”...的话，只需修改np.savez中传递的参数即可


np.savez('testz_name.npz', arr1 = a, arr2 = b, arr3 = c)

## 读取

In [17]:
out = np.load("test.npy")
print(out)

# 取.npz文件时使用np.load()函数 返回的是一个类似于字典的对象，因此可以通过数组名作为关键字对多个数组进行访问。
outz = np.load('testz.npz')
print(outz.files) # 
a1 = outz[outz.files[0]]
print(a1)


out_name = np.load('testz_name.npz')
print('arr1: ',out_name['arr1'])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
['arr_0', 'arr_1', 'arr_2']
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr1:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
